### 
GET http://localhost:3001/api/v1/workouts


###
GET  http://localhost:3001/api/v1/workouts/1cbbefe9-399d-44a3-8aee-ede584aa818d

###
POST http://localhost:3001/api/v1/workouts

{
  "name": "Core Buster",
  "mode": "AMRAP 20",
  "equipment": [
    "rack",
    "barbell",
    "abmat"
  ],
  "exercises": [
    "15 toes to bars",
    "10 thrusters",
    "30 abmat sit-ups"
  ],
  "trainerTips": [
    "Split your toes to bars into two sets maximum",
    "Go unbroken on the thrusters",
    "Take the abmat sit-ups as a chance to normalize your breath"
  ]
}


###
PATCH http://localhost:3001/api/v1/workouts/1cbbefe9-399d-44a3-8aee-ede584aa818d

{
  "name": "Pato pampa",
  "mode": "Full",
  "equipment": [
    "pato",
    "pato333",
  ], 
  "trainerTips": [
    "Split your toes to bars into two sets maximum",
    "Go unbroken on the thrusters",
    "Take the abmat sit-ups as a chance to normalize your breath"
  ]
}
###
DELETE  http://localhost:3001/api/v1/workouts/10